name: "Drupal Module Tests + Coverage"
description: "Configures Composer dependencies, sets up a Drupal site, and runs PHPUnit with coverage."

inputs:
  drupal_version:
    description: "Drupal version to install"
    required: false
    default: "10"
  module_name:
    description: "Name of the custom module"
    required: true
  repo_name:
    description: "Name of the custom module repository"
    required: true
  repo_org: # todo: set default
    description: "Name of the custom module repository organization"
    required: true
  repo_ref:
    description: "Name of the custom module ref to checkout"
    required: true
  module_vendor:
    description: "Vendor name of the custom module"
    required: true
  module_dir:
    description: "Directory path for the custom module"
    required: false
    default: "web/modules/acp-composer"
  project_dir: # todo: confirm if needed
    description: "Directory to install the Drupal project"
    required: false
    default: "drupal-site"
  composer_repositories:
    description: "List of repositories to add (supports YAML array format)"
    required: false
    default: ""
  composer_gh_pat:
    description: "GitHub Personal Access Token for Composer"
    required: false
  simpletest_db:
    description: "Database URL for Simpletest"
    required: false
    default: "mysql://root:root@mysql:3306/drupal_test"

runs:
  using: "composite"
  steps:
    - name: Checkout full action repository
      uses: actions/checkout@v4
      with:
        repository: nbey/drupal-custom-module-ci
        path: ${{ runner.temp }}/action-full-repo
        token: ${{ github.token }}
        clean: true

    - run: ls -alh ${{ runner.temp }}/action-full-repo
      shell: bash

    - name: Run Node.js Setup Script
      shell: bash
      env:
        DRUPAL_VERSION: ${{ inputs.drupal_version }}
        DRUPAL_PROJECT_DIR: ${{ inputs.project_dir }}
        DRUPAL_CUSTOM_MODULE_DIR: ${{ inputs.module_dir }}
        CUSTOM_MODULE_NAME: ${{ inputs.module_name }}
        CUSTOM_MODULE_REPOSITORY_ORG: ${{ inputs.repo_org }}
        CUSTOM_MODULE_REPOSITORY_NAME: ${{ inputs.repo_name }}
        CUSTOM_MODULE_REPOSITORY_REF: ${{ inputs.repo_ref }}
        CUSTOM_MODULE_VENDOR: ${{ inputs.module_vendor }}
        COMPOSER_REPOSITORIES: ${{ inputs.composer_repositories }}
        COMPOSER_GH_PAT: ${{ inputs.composer_gh_pat }}

      run: node ${{ runner.temp }}/action-full-repo/scripts/setup-composer.js

    - name: Composer Install
      uses: ramsey/composer-install@v3
      with:
        working-directory: ${{ inputs.project_dir }}
        composer-options: "--no-interaction --prefer-dist"

    - name: Install Drupal Site
      shell: bash
      working-directory: ${{ inputs.project_dir }}
      env:
        SIMPLETEST_DB: ${{ inputs.simpletest_db }}
      run: |
        ./vendor/bin/drush site:install testing --db-url="${SIMPLETEST_DB}" --account-name=admin --account-pass=admin -y
        ./vendor/bin/drush role:perm:add anonymous 'access content'

    - name: Create Test Output Dirs
      shell: bash
      run: |
        mkdir -p /tmp/coverage
        mkdir -p /tmp/simpletest_browser_output

    - name: Set Environment Variables for PHPUnit
      shell: bash
      run: |
        echo 'MINK_DRIVER_ARGS_WEBDRIVER=["chrome", {"browserName": "chrome", "goog:chromeOptions": {"args": ["--headless=new", "--no-sandbox", "--disable-gpu", "--window-size=1280,1024", "--user-data-dir=/tmp/chrome-profile-${RANDOM}"]}}, "http://localhost:9515"]' >> $GITHUB_ENV

    - name: Run PHP Server
      shell: bash
      working-directory: ${{ inputs.project_dir }}
      run: php -S 127.0.0.1:80 -t web/ &

    - name: Run PHPUnit with coverage (all tests)
      shell: bash
      working-directory: ${{ inputs.project_dir }}/web
      continue-on-error: true
      run: |
        ../vendor/bin/phpunit -c core/phpunit.xml.dist -v --color --testdox \
        --coverage-html /tmp/coverage \
        ../${{ inputs.module_dir }}/${{ inputs.module_name }}/tests/src

    - name: Debug
      if: failure()
      uses: mxschmitt/action-tmate@v3

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: /tmp/coverage/
